package com.linuxterminal.mobile.proot

import android.content.Context
import android.util.Log
import com.linuxterminal.mobile.terminal.Pty
import java.io.File

/**
 * Builds and launches the PRoot command to run Ubuntu.
 * Uses a bash startup script approach (like OnecodeTerminal):
 * 1. Run bash with a generated startup script
 * 2. The script installs Ubuntu rootfs if needed (using busybox tar)
 * 3. Then logs into Ubuntu via PRoot
 *
 * This approach is more robust than calling PRoot directly because:
 * - bash handles environment setup
 * - busybox handles tar.xz extraction
 * - The script can handle errors gracefully
 */
class PRootRunner(private val context: Context, private val envSetup: EnvironmentSetup) {

    companion object {
        private const val TAG = "PRootRunner"
    }

    /** Get the path to the bash binary */
    private fun getBashPath(): String {
        return File(envSetup.binDir, "bash").absolutePath
    }

    /** Get the path to the proot binary */
    private fun getProotPath(): String {
        return File(envSetup.binDir, "proot").absolutePath
    }

    /** Get the path to the busybox binary */
    private fun getBusyboxPath(): String {
        return File(envSetup.binDir, "busybox").absolutePath
    }

    /** Get environment variables for the terminal session */
    fun getEnvironment(): Map<String, String> {
        return mapOf(
            "PATH" to "${envSetup.binDir.absolutePath}:${System.getenv("PATH")}",
            "HOME" to envSetup.filesDir.absolutePath,
            "PREFIX" to envSetup.usrDir.absolutePath,
            "LD_LIBRARY_PATH" to "${envSetup.nativeLibDir}:${envSetup.binDir.absolutePath}",
            "PROOT_LOADER" to File(envSetup.binDir, "loader").absolutePath,
            "TMPDIR" to envSetup.tmpDir.absolutePath,
            "PROOT_TMP_DIR" to envSetup.tmpDir.absolutePath,
            "TERM" to "xterm-256color",
            "LANG" to "en_US.UTF-8",
            "LANGUAGE" to "en_US:en",
            "SHELL" to "/bin/bash",
            "USER" to "root",
            "LOGNAME" to "root",
            "HOSTNAME" to "ubuntu"
        )
    }

    /**
     * Generate the startup script (common.sh) that handles:
     * 1. Installing Ubuntu rootfs (extracting tarball if needed)
     * 2. Configuring the Ubuntu environment
     * 3. Logging into Ubuntu via PRoot
     *
     * All paths are evaluated by Kotlin at generation time.
     * No shell variables — the resulting script has hardcoded paths.
     */
    fun generateStartScript(): String {
        val prootPath = getProotPath()
        val busyboxPath = getBusyboxPath()
        val tarballPath = envSetup.getRootfsTarballPath()
        val ubuntuHome = envSetup.ubuntuPath
        val tmpDirPath = envSetup.tmpDir.absolutePath
        val nativeLibDirPath = envSetup.nativeLibDir
        val binDirPath = envSetup.binDir.absolutePath
        val filesDirPath = envSetup.filesDir.absolutePath
        val systemPath = System.getenv("PATH") ?: "/system/bin"

        return """
#!/system/bin/sh
# TuxBox startup script - generated by PRootRunner

export PATH="$binDirPath:$systemPath"
export HOME="$filesDirPath"
export LD_LIBRARY_PATH="$nativeLibDirPath:$binDirPath"
export PROOT_LOADER="$binDirPath/loader"
export PROOT_TMP_DIR="$tmpDirPath"
export TMPDIR="$tmpDirPath"
export TERM="xterm-256color"
export LANG="en_US.UTF-8"

# Check if Ubuntu is already installed
if [ ! -f "$ubuntuHome/.onecode_installed_ok" ]; then
    echo "Installing Ubuntu rootfs..."
    mkdir -p "$ubuntuHome"

    if [ -f "$tarballPath" ]; then
        echo "Extracting rootfs from tarball..."
        "$busyboxPath" tar xf "$tarballPath" -C "$ubuntuHome" 2>&1 || {
            echo "Extraction failed, trying with system tar..."
            tar xf "$tarballPath" -C "$ubuntuHome" 2>&1
        }

        if [ -d "$ubuntuHome/bin" ]; then
            echo "Rootfs extracted successfully."
            touch "$ubuntuHome/.onecode_installed_ok"
        else
            echo "ERROR: Rootfs extraction failed!"
            echo "Falling back to basic shell."
            exec /system/bin/sh
        fi
    else
        echo "ERROR: Rootfs tarball not found at $tarballPath"
        echo "Falling back to basic shell."
        exec /system/bin/sh
    fi
fi

# Configure Ubuntu environment
if [ ! -f "$ubuntuHome/etc/resolv.conf" ] || [ ! -s "$ubuntuHome/etc/resolv.conf" ]; then
    echo "nameserver 8.8.8.8" > "$ubuntuHome/etc/resolv.conf"
    echo "nameserver 8.8.4.4" >> "$ubuntuHome/etc/resolv.conf"
fi

# Create necessary directories
mkdir -p "$ubuntuHome/dev" "$ubuntuHome/proc" "$ubuntuHome/sys" "$ubuntuHome/tmp" "$ubuntuHome/root"

# Set hostname if not set
if [ ! -f "$ubuntuHome/etc/hostname" ]; then
    echo "ubuntu" > "$ubuntuHome/etc/hostname"
fi

# Create /etc/passwd if not present
if [ ! -f "$ubuntuHome/etc/passwd" ]; then
    echo "root:x:0:0:root:/root:/bin/bash" > "$ubuntuHome/etc/passwd"
fi

# Create /etc/group if not present
if [ ! -f "$ubuntuHome/etc/group" ]; then
    echo "root:x:0:" > "$ubuntuHome/etc/group"
fi

# Create /etc/hosts if not present
if [ ! -f "$ubuntuHome/etc/hosts" ]; then
    echo "127.0.0.1 localhost" > "$ubuntuHome/etc/hosts"
    echo "127.0.1.1 ubuntu" >> "$ubuntuHome/etc/hosts"
fi

# Login to Ubuntu via PRoot
echo "Starting Ubuntu..."
exec "$prootPath" \
    -r "$ubuntuHome" \
    -b /dev \
    -b /proc \
    -b /sys \
    -b /dev/urandom:/dev/random \
    -b /proc/self/fd:/dev/fd \
    -b /proc/self/fd/0:/dev/stdin \
    -b /proc/self/fd/1:/dev/stdout \
    -b /proc/self/fd/2:/dev/stderr \
    -b "$binDirPath:/usr/local/bin" \
    --link2symlink \
    --kill-on-exit \
    -w /root \
    -0 root \
    /usr/bin/env -i \
    HOME=/root \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TERM=xterm-256color \
    LANG=C.UTF-8 \
    LANGUAGE=en_US:en \
    SHELL=/bin/bash \
    USER=root \
    LOGNAME=root \
    HOSTNAME=ubuntu \
    /bin/bash -l
""".trimIndent()
    }

    /** Write the startup script to a file */
    fun writeStartScript(): File {
        val scriptFile = File(envSetup.filesDir, "common.sh")
        scriptFile.writeText(generateStartScript())
        scriptFile.setExecutable(true, false)
        Log.i(TAG, "Startup script written to ${scriptFile.absolutePath}")
        return scriptFile
    }

    /**
     * Build the command to start the terminal session.
     * Uses bash with the startup script.
     */
    fun buildCommand(): List<String> {
        val scriptFile = writeStartScript()
        val bashPath = getBashPath()

        return if (File(bashPath).exists() && File(bashPath).canExecute()) {
            listOf(bashPath, "-c", ". ${scriptFile.absolutePath}")
        } else {
            // Fallback to system sh
            listOf("/system/bin/sh", scriptFile.absolutePath)
        }
    }

    /** Check if PRoot is ready */
    fun isReady(): Boolean {
        val proot = File(envSetup.binDir, "proot")
        val busybox = File(envSetup.binDir, "busybox")
        val bash = File(envSetup.binDir, "bash")
        return proot.exists() && proot.canExecute() &&
               busybox.exists() && busybox.canExecute()
    }

    

    /**
     * Start the terminal session using PTY.
     * Returns a Pty object for I/O.
     */
    fun startSession(): Pty? {
        val cmd = buildCommand().toTypedArray()
        val env = getEnvironment()
        val cwd = File(envSetup.filesDir.absolutePath)

        return try {
            Pty.start(cmd, env, cwd)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to start session", e)
            null
        }
    }
}
