package com.linuxterminal.mobile.proot

import android.content.Context
import android.util.Log
import com.linuxterminal.mobile.terminal.Pty
import java.io.File

/**
 * Builds and launches the PRoot command to run Ubuntu.
 * Uses a bash startup script approach (like OnecodeTerminal):
 * 1. Run bash with a generated startup script
 * 2. The script installs Ubuntu rootfs if needed (using busybox tar)
 * 3. Then logs into Ubuntu via PRoot
 *
 * This approach is more robust than calling PRoot directly because:
 * - bash handles environment setup
 * - busybox handles tar.xz extraction
 * - The script can handle errors gracefully
 */
class PRootRunner(private val context: Context, private val envSetup: EnvironmentSetup) {

    companion object {
        private const val TAG = "PRootRunner"
    }

    /** Get the path to the bash binary */
    private fun getBashPath(): String {
        return File(envSetup.binDir, "bash").absolutePath
    }

    /** Get the path to the proot binary */
    private fun getProotPath(): String {
        return File(envSetup.binDir, "proot").absolutePath
    }

    /** Get the path to the busybox binary */
    private fun getBusyboxPath(): String {
        return File(envSetup.binDir, "busybox").absolutePath
    }

    /** Get environment variables for the terminal session */
    fun getEnvironment(): Map<String, String> {
        return mapOf(
            "PATH" to "${envSetup.binDir.absolutePath}:${System.getenv("PATH")}",
            "HOME" to envSetup.filesDir.absolutePath,
            "PREFIX" to envSetup.usrDir.absolutePath,
            "LD_LIBRARY_PATH" to "${envSetup.nativeLibDir}:${envSetup.binDir.absolutePath}",
            "PROOT_LOADER" to File(envSetup.binDir, "loader").absolutePath,
            "TMPDIR" to envSetup.tmpDir.absolutePath,
            "PROOT_TMP_DIR" to envSetup.tmpDir.absolutePath,
            "TERM" to "xterm-256color",
            "LANG" to "en_US.UTF-8",
            "LANGUAGE" to "en_US:en",
            "SHELL" to "/bin/bash",
            "USER" to "root",
            "LOGNAME" to "root",
            "HOSTNAME" to "ubuntu"
        )
    }

    /**
     * Generate the startup script (common.sh) that handles:
     * 1. Installing Ubuntu rootfs (extracting tarball if needed)
     * 2. Configuring the Ubuntu environment
     * 3. Logging into Ubuntu via PRoot
     *
     * All paths are evaluated by Kotlin at generation time.
     * No shell variables — the resulting script has hardcoded paths.
     */
    fun generateStartScript(): String {
        val prootPath = getProotPath()
        val busyboxPath = getBusyboxPath()
        val tarballPath = envSetup.getRootfsTarballPath()
        val ubuntuHome = envSetup.ubuntuPath
        val tmpDirPath = envSetup.tmpDir.absolutePath
        val nativeLibDirPath = envSetup.nativeLibDir
        val binDirPath = envSetup.binDir.absolutePath
        val filesDirPath = envSetup.filesDir.absolutePath
        val systemPath = System.getenv("PATH") ?: "/system/bin"
        val ubuntuName = "ubuntu-noble-aarch64"
        val tmpExtractDir = "$ubuntuHome.install.tmp"

        return """
#!/system/bin/sh
# TuxBox startup script - generated by PRootRunner
# Based on OnecodeTerminal's install_ubuntu approach

export PATH="$binDirPath:$systemPath"
export HOME="$filesDirPath"
export LD_LIBRARY_PATH="$nativeLibDirPath:$binDirPath"
export PROOT_LOADER="$binDirPath/loader"
export PROOT_TMP_DIR="$tmpDirPath"
export TMPDIR="$tmpDirPath"
export TERM="xterm-256color"
export LANG="en_US.UTF-8"

# Check if Ubuntu is already installed
if [ -f "$ubuntuHome/.onecode_installed_ok" ]; then
    :
else
    # Check if already extracted but not marked
    if [ -f "$ubuntuHome/etc/issue.net" ]; then
        echo "ok" > "$ubuntuHome/.onecode_installed_ok" 2>/dev/null || true
    else
        echo "Installing Ubuntu rootfs..."
        if [ ! -f "$tarballPath" ]; then
            echo "ERROR: Rootfs tarball not found at $tarballPath"
            echo "Falling back to basic shell."
            exec /system/bin/sh
        fi

        # Clean up any previous failed extraction
        rm -rf "$tmpExtractDir" 2>/dev/null
        mkdir -p "$tmpExtractDir" 2>/dev/null

        echo "Extracting rootfs from tarball..."
        # Redirect stderr to /dev/null — busybox tar prints "can't create node"
        # warnings for device nodes which is normal on non-rooted Android
        "$busyboxPath" tar xf "$tarballPath" -C "$tmpExtractDir"/ >/dev/null 2>&1

        echo "Extraction complete"

        # Strip top-level directory if present (tarball contains ubuntu-noble-aarch64/)
        if [ -d "$tmpExtractDir/$ubuntuName" ]; then
            mv "$tmpExtractDir/$ubuntuName"/* "$tmpExtractDir"/ 2>/dev/null
            rm -rf "$tmpExtractDir/$ubuntuName" 2>/dev/null
        fi

        # Verify extraction produced expected files
        if [ ! -d "$tmpExtractDir/bin" ]; then
            echo "ERROR: Rootfs extraction failed - /bin directory missing"
            rm -rf "$tmpExtractDir" 2>/dev/null
            echo "Falling back to basic shell."
            exec /system/bin/sh
        fi

        # Configure Ubuntu environment
        mkdir -p "$tmpExtractDir/root" 2>/dev/null
        echo 'export ANDROID_DATA=/home/' >> "$tmpExtractDir/root/.bashrc"
        echo 'export PS1="root@localhost:~# "' >> "$tmpExtractDir/root/.bashrc"
        mkdir -p "$tmpExtractDir/etc" 2>/dev/null
        echo 'nameserver 8.8.8.8' > "$tmpExtractDir/etc/resolv.conf"
        echo "ok" > "$tmpExtractDir/.onecode_installed_ok" 2>/dev/null || true

        # Move temp directory to final location
        rm -rf "$ubuntuHome" 2>/dev/null
        mv "$tmpExtractDir" "$ubuntuHome" 2>/dev/null
        if [ ! -d "$ubuntuHome" ]; then
            echo "ERROR: Failed to move rootfs to final location"
            rm -rf "$tmpExtractDir" 2>/dev/null
            echo "Falling back to basic shell."
            exec /system/bin/sh
        fi

        # Delete tarball to save space
        rm -f "$tarballPath" 2>/dev/null
    fi
fi

# Ensure resolv.conf exists
mkdir -p "$ubuntuHome/etc" 2>/dev/null
echo 'nameserver 8.8.8.8' > "$ubuntuHome/etc/resolv.conf"

# Create necessary directories
mkdir -p "$ubuntuHome/dev" "$ubuntuHome/proc" "$ubuntuHome/sys" "$ubuntuHome/tmp" "$ubuntuHome/root" 2>/dev/null

# Login to Ubuntu via PRoot
echo "Starting Ubuntu..."
exec "$prootPath" \
    -r "$ubuntuHome" \
    -b /dev \
    -b /proc \
    -b /sys \
    -b /dev/urandom:/dev/random \
    -b /proc/self/fd:/dev/fd \
    -b /proc/self/fd/0:/dev/stdin \
    -b /proc/self/fd/1:/dev/stdout \
    -b /proc/self/fd/2:/dev/stderr \
    -b "$binDirPath:/usr/local/bin" \
    --link2symlink \
    --kill-on-exit \
    -w /root \
    -0 root \
    /usr/bin/env -i \
    HOME=/root \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TERM=xterm-256color \
    LANG=C.UTF-8 \
    LANGUAGE=en_US:en \
    SHELL=/bin/bash \
    USER=root \
    LOGNAME=root \
    HOSTNAME=ubuntu \
    /bin/bash -l
""".trimIndent()
    }

    /** Write the startup script to a file */
    fun writeStartScript(): File {
        val scriptFile = File(envSetup.filesDir, "common.sh")
        scriptFile.writeText(generateStartScript())
        scriptFile.setExecutable(true, false)
        Log.i(TAG, "Startup script written to ${scriptFile.absolutePath}")
        return scriptFile
    }

    /**
     * Build the command to start the terminal session.
     * Uses bash with the startup script.
     */
    fun buildCommand(): List<String> {
        val scriptFile = writeStartScript()
        val bashPath = getBashPath()

        return if (File(bashPath).exists() && File(bashPath).canExecute()) {
            listOf(bashPath, "-c", ". ${scriptFile.absolutePath}")
        } else {
            // Fallback to system sh
            listOf("/system/bin/sh", scriptFile.absolutePath)
        }
    }

    /** Check if PRoot is ready */
    fun isReady(): Boolean {
        val proot = File(envSetup.binDir, "proot")
        val busybox = File(envSetup.binDir, "busybox")
        val bash = File(envSetup.binDir, "bash")
        return proot.exists() && proot.canExecute() &&
               busybox.exists() && busybox.canExecute()
    }

    

    /**
     * Start the terminal session using PTY.
     * Returns a Pty object for I/O.
     */
    fun startSession(): Pty? {
        val cmd = buildCommand().toTypedArray()
        val env = getEnvironment()
        val cwd = File(envSetup.filesDir.absolutePath)

        return try {
            Pty.start(cmd, env, cwd)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to start session", e)
            null
        }
    }
}
